mutation create_user(
  $email: String!
  $password: String!
  $first_name: String
  $last_name: String
  $external_id: ID
) {
  user_create(
    user: {
      email: $email
      password: $password
      first_name: $first_name
      last_name: $last_name
      external_id: $external_id
    }
  ) {
    id
    email
    first_name
    last_name
    external_id

    jwt_token(algorithm: HS256)

    portal: profiles(profile_type: "modules/portal/portal") {
      is_enabled: property_boolean(name: "is_enabled")
      primary_account_holder: property_boolean(name: "primary_account_holder")
      permission_level: property(name: "permission_level")
    }

    crm_contact: profiles(profile_type: "modules/insites_core/crm_contact") {
      id
      company_uuid: property(name: "company_uuid")
      mobile_phone_number: property(name: "mobile_phone_number")
      mobile_phone_country_code: property(name: "mobile_phone_country_code")
      company: related_record(
        table: "modules/insites_core/crm_company"
        foreign_property: "uuid"
        join_on_property: "company_uuid"
      ) {
        company_name: property(name: "company_name")
      }
    }
  }
}
